spring:
  cloud:
    gateway:
      routes:
        - id: query_route_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
server:
  port: 8090
