spring:
  cloud:
    gateway:
      routes:
        - id: query_route_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: query_route_qq
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

