spring:
  cloud:
    gateway:
      routes:
        - id: query_route_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: product_route
          uri: lb://gxmail-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://gxmail-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
server:
  port: 8090
